### ISSUE TITLE
can you save one of the 4 generated images instead of all 4 ?

### ISSUE THREAD

**Issue by raymerjacque** [basitng/midjourney-py#1]
can you select and save one of the 4 generated images instead of all 4 ?

**Comment by basitng** [comment]
You can upscale one of the four images generated depending on your choice. You could use the upscale method from the mid-journey.

**Comment by basitng** [comment]
`python` 

from midjourney import Midjourney

midjourney = Midjourney(
    api_key="API_KEY", callback_uri="")

seed = midjourney.imagine("Monotone illustration of cat in style of Shiny Kistch pop art")

upscale = midjourney.upscale(
    task_id=seed, position="2")

print(upscale)
