### ISSUE TITLE
Crazy insane pricing...

### ISSUE THREAD

**Issue by raymerjacque** [basitng/midjourney-py#2]
this API you are using, the prices are fraking crazy... its like 1 dollar per image.... wtf ?

**Comment by basitng** [comment]
I think the API is fair for 20 dollars they give you access to generate 210 images. If you have a better service that has good pricing I will be glad to migrate please email me at basitng2004@gmail.com if you have any. For now, I will be sticking with the API because is fair enough. Thanks for your insight 👍

**Comment by raymerjacque** [comment]
https://www.imagine.art/  < ---- 60 usd a year, unlimited generations.
https://app.prodia.com/ < ---- 48 usd a year, unlimited generations.
https://www.midjourney.com/account/ < --- 24usd a month, unlimited generations...

and you are charging 50 usd cents per image and you dont even have an easy GUi setup system... good luck with that, everyone else is out pricing you.

**Comment by basitng** [comment]
Wow this amazing thanks!

**Comment by basitng** [comment]
Thank you for sharing the links to various web services that offer unlimited generations for different prices. I understand your concern about the pricing of our service and the lack of an easy GUI setup system.

We appreciate your feedback and understand that competitive pricing is an important factor for users when considering different options. We continuously evaluate our pricing structure to ensure it aligns with market standards and provides value to our customers.

Regarding the absence of an easy GUI setup system, we apologize for any inconvenience it may have caused. We are constantly working on improving our platform and user experience. We take your feedback seriously and will consider it as we continue to enhance our services.

If you have any further suggestions or specific features you would like to see in our service, please let us know. We value your input and aim to provide the best possible experience for our users.

Thank you for bringing this to our attention, and we appreciate your support.

**Comment by raymerjacque** [comment]
i use imaginepy, i made an api wrapper for it and then i created a GUI... i pay 60usd a year and now everyone on my project can generate unlimited images... i dont make it public, if i did youd be out of business. here is the gui i made :
![Screenshot 2023-07-01 213655](https://github.com/basitng/midjourney-py/assets/4136088/12238204-d488-4df4-9c33-acf6086d82a4)

i also made the same for Prodia, this one is just 48usd a year and unlimited images :
![Screenshot 2023-07-08 144816](https://github.com/basitng/midjourney-py/assets/4136088/6a7c1b3a-eca5-4406-ad54-0c275ae513c8)

you see what i mean about easy to use GUI's... i made both from API. they run on both windows and linux.

my point is, its becoming cheaper and cheaper and more and more people are now hosting image AI generators. you can now download fine tuned A.I models here : https://civitai.com/  and host it yourself and create your own A.I pretty easily, they even provide the backend framework...

50usd cents per image, you wont last long, you are quickly being outpriced. you may get a few sales, there other guys have millions of users... you think 60usd a year is too little, its not when you have 2.3 million subscribers...

think smart, dont think greedy...
